# Generated by Django 2.2.7 on 2019-12-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=512)),
                ('view_name', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('form_data', models.TextField(blank=True, null=True)),
                ('file_params', models.TextField(blank=True, null=True)),
                ('results', models.TextField()),
                ('accessed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
