# Generated by Django 2.2.7 on 2019-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogs',
            name='host_ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='accesslogs',
            name='http_x_forwarded_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
