# Generated by Django 2.2.7 on 2020-09-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_logger', '0002_auto_20191206_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogs',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
